// Code generated by protoc-gen-gogo.
// source: dir.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	dir.proto
	manifest.proto
	node.proto
	stmt.proto

It has these top-level messages:
	PeerInfo
	PublisherInfo
	RegisterPeer
	LookupPeerRequest
	LookupPeerResponse
	ListPeersRequest
	ListPeersResponse
	ListNamespacesRequest
	ListNamespacesResponse
	Manifest
	ManifestBody
	NodeManifest
	StreamEnd
	StreamError
	NodeInfoRequest
	NodeInfo
	Ping
	Pong
	QueryRequest
	QueryResult
	QueryResultValue
	SimpleValue
	CompoundValue
	KeyValuePair
	DataRequest
	DataResult
	DataObject
	PushRequest
	PushResponse
	PushAccept
	PushReject
	PushValue
	PushEnd
	Statement
	StatementBody
	SimpleStatement
	CompoundStatement
	EnvelopeStatement
	ArchiveStatement
*/
package proto

import proto1 "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type PeerInfo struct {
	Id   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr [][]byte `protobuf:"bytes,2,rep,name=addr" json:"addr,omitempty"`
}

func (m *PeerInfo) Reset()                    { *m = PeerInfo{} }
func (m *PeerInfo) String() string            { return proto1.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()               {}
func (*PeerInfo) Descriptor() ([]byte, []int) { return fileDescriptorDir, []int{0} }

type PublisherInfo struct {
	Id         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespaces []string `protobuf:"bytes,2,rep,name=namespaces" json:"namespaces,omitempty"`
}

func (m *PublisherInfo) Reset()                    { *m = PublisherInfo{} }
func (m *PublisherInfo) String() string            { return proto1.CompactTextString(m) }
func (*PublisherInfo) ProtoMessage()               {}
func (*PublisherInfo) Descriptor() ([]byte, []int) { return fileDescriptorDir, []int{1} }

// /mediachain/dir/register
type RegisterPeer struct {
	Info      *PeerInfo      `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Publisher *PublisherInfo `protobuf:"bytes,2,opt,name=publisher" json:"publisher,omitempty"`
}

func (m *RegisterPeer) Reset()                    { *m = RegisterPeer{} }
func (m *RegisterPeer) String() string            { return proto1.CompactTextString(m) }
func (*RegisterPeer) ProtoMessage()               {}
func (*RegisterPeer) Descriptor() ([]byte, []int) { return fileDescriptorDir, []int{2} }

func (m *RegisterPeer) GetInfo() *PeerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *RegisterPeer) GetPublisher() *PublisherInfo {
	if m != nil {
		return m.Publisher
	}
	return nil
}

// /mediachain/dir/lookup
type LookupPeerRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *LookupPeerRequest) Reset()                    { *m = LookupPeerRequest{} }
func (m *LookupPeerRequest) String() string            { return proto1.CompactTextString(m) }
func (*LookupPeerRequest) ProtoMessage()               {}
func (*LookupPeerRequest) Descriptor() ([]byte, []int) { return fileDescriptorDir, []int{3} }

type LookupPeerResponse struct {
	Peer *PeerInfo `protobuf:"bytes,1,opt,name=peer" json:"peer,omitempty"`
}

func (m *LookupPeerResponse) Reset()                    { *m = LookupPeerResponse{} }
func (m *LookupPeerResponse) String() string            { return proto1.CompactTextString(m) }
func (*LookupPeerResponse) ProtoMessage()               {}
func (*LookupPeerResponse) Descriptor() ([]byte, []int) { return fileDescriptorDir, []int{4} }

func (m *LookupPeerResponse) GetPeer() *PeerInfo {
	if m != nil {
		return m.Peer
	}
	return nil
}

// /mediachain/dir/list
type ListPeersRequest struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (m *ListPeersRequest) Reset()                    { *m = ListPeersRequest{} }
func (m *ListPeersRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListPeersRequest) ProtoMessage()               {}
func (*ListPeersRequest) Descriptor() ([]byte, []int) { return fileDescriptorDir, []int{5} }

type ListPeersResponse struct {
	Peers []string `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
}

func (m *ListPeersResponse) Reset()                    { *m = ListPeersResponse{} }
func (m *ListPeersResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListPeersResponse) ProtoMessage()               {}
func (*ListPeersResponse) Descriptor() ([]byte, []int) { return fileDescriptorDir, []int{6} }

// /mediachain/dir/listns
type ListNamespacesRequest struct {
}

func (m *ListNamespacesRequest) Reset()                    { *m = ListNamespacesRequest{} }
func (m *ListNamespacesRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListNamespacesRequest) ProtoMessage()               {}
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) { return fileDescriptorDir, []int{7} }

type ListNamespacesResponse struct {
	Namespaces []string `protobuf:"bytes,1,rep,name=namespaces" json:"namespaces,omitempty"`
}

func (m *ListNamespacesResponse) Reset()                    { *m = ListNamespacesResponse{} }
func (m *ListNamespacesResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListNamespacesResponse) ProtoMessage()               {}
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) { return fileDescriptorDir, []int{8} }

func init() {
	proto1.RegisterType((*PeerInfo)(nil), "proto.PeerInfo")
	proto1.RegisterType((*PublisherInfo)(nil), "proto.PublisherInfo")
	proto1.RegisterType((*RegisterPeer)(nil), "proto.RegisterPeer")
	proto1.RegisterType((*LookupPeerRequest)(nil), "proto.LookupPeerRequest")
	proto1.RegisterType((*LookupPeerResponse)(nil), "proto.LookupPeerResponse")
	proto1.RegisterType((*ListPeersRequest)(nil), "proto.ListPeersRequest")
	proto1.RegisterType((*ListPeersResponse)(nil), "proto.ListPeersResponse")
	proto1.RegisterType((*ListNamespacesRequest)(nil), "proto.ListNamespacesRequest")
	proto1.RegisterType((*ListNamespacesResponse)(nil), "proto.ListNamespacesResponse")
}

func init() { proto1.RegisterFile("dir.proto", fileDescriptorDir) }

var fileDescriptorDir = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x50, 0xcb, 0x4e, 0xeb, 0x30,
	0x10, 0x55, 0x72, 0xdb, 0x2b, 0x3c, 0x94, 0x47, 0xad, 0x02, 0x59, 0x20, 0x54, 0x4d, 0x37, 0x65,
	0x13, 0xa1, 0xb2, 0x81, 0x15, 0x6b, 0xa4, 0x0a, 0x55, 0xfe, 0x83, 0x14, 0x4f, 0x8b, 0x05, 0xc4,
	0xc6, 0x93, 0xfc, 0x3f, 0xb2, 0x9b, 0xb4, 0x21, 0x52, 0x57, 0x89, 0x67, 0xce, 0x6b, 0x0e, 0x08,
	0x6d, 0x7c, 0xee, 0xbc, 0xad, 0xac, 0x1c, 0xc6, 0x0f, 0xe6, 0x70, 0xb2, 0x22, 0xf2, 0xaf, 0xe5,
	0xc6, 0xca, 0x73, 0x48, 0x8d, 0xce, 0x92, 0x69, 0x32, 0x17, 0x2a, 0x35, 0x5a, 0x4a, 0x18, 0x14,
	0x5a, 0xfb, 0x2c, 0x9d, 0xfe, 0x9b, 0x8f, 0x54, 0xfc, 0xc7, 0x17, 0x38, 0x5b, 0xd5, 0xeb, 0x2f,
	0xc3, 0x1f, 0x47, 0x48, 0x77, 0x00, 0x65, 0xf1, 0x4d, 0xec, 0x8a, 0x77, 0xe2, 0x48, 0x15, 0xaa,
	0x33, 0xc1, 0x2d, 0x8c, 0x14, 0x6d, 0x0d, 0x57, 0xe4, 0x83, 0xb1, 0x9c, 0xc1, 0xc0, 0x94, 0x1b,
	0x1b, 0x15, 0x4e, 0x17, 0x17, 0xbb, 0x74, 0x79, 0x9b, 0x49, 0xc5, 0xa5, 0x5c, 0x80, 0x70, 0xad,
	0x6b, 0x96, 0x46, 0xe4, 0xa4, 0x45, 0x76, 0xd3, 0xa8, 0x03, 0x0c, 0x67, 0x30, 0x5e, 0x5a, 0xfb,
	0x59, 0xbb, 0xa0, 0xa5, 0xe8, 0xa7, 0x26, 0xae, 0xfa, 0x69, 0xf1, 0x19, 0x64, 0x17, 0xc4, 0xce,
	0x96, 0x4c, 0x21, 0x93, 0x23, 0xf2, 0x47, 0x33, 0x85, 0x25, 0x3e, 0xc0, 0xe5, 0xd2, 0x70, 0x15,
	0xa6, 0xdc, 0xca, 0xdf, 0x82, 0xd8, 0x9f, 0xda, 0xb8, 0x1c, 0x06, 0x78, 0x0f, 0xe3, 0x0e, 0xa3,
	0xf1, 0x9a, 0xc0, 0x30, 0xc8, 0x71, 0x96, 0xc4, 0xaa, 0x76, 0x0f, 0xbc, 0x81, 0xab, 0x00, 0x7d,
	0xdb, 0xf7, 0xd6, 0x38, 0xe0, 0x13, 0x5c, 0xf7, 0x17, 0x8d, 0xd0, 0xdf, 0xe2, 0x93, 0x7e, 0xf1,
	0xeb, 0xff, 0xf1, 0x8a, 0xc7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x90, 0x83, 0x80, 0xd8, 0x04,
	0x02, 0x00, 0x00,
}
