// Code generated by protoc-gen-gogo.
// source: node.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// node/ping
type Ping struct {
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto1.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}

type Pong struct {
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto1.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}

func init() {
	proto1.RegisterType((*Ping)(nil), "proto.Ping")
	proto1.RegisterType((*Pong)(nil), "proto.Pong")
}
