// Code generated by protoc-gen-gogo.
// source: node.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// node/ping
type Ping struct {
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto1.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{0} }

type Pong struct {
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto1.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{1} }

// node/query
type QueryRequest struct {
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto1.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{2} }

type QueryResult struct {
	// Types that are valid to be assigned to Result:
	//	*QueryResult_Value
	//	*QueryResult_End
	//	*QueryResult_Error
	Result isQueryResult_Result `protobuf_oneof:"result"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto1.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{3} }

type isQueryResult_Result interface {
	isQueryResult_Result()
}

type QueryResult_Value struct {
	Value *QueryResultValue `protobuf:"bytes,1,opt,name=value,oneof"`
}
type QueryResult_End struct {
	End *QueryResultEnd `protobuf:"bytes,2,opt,name=end,oneof"`
}
type QueryResult_Error struct {
	Error *QueryResultError `protobuf:"bytes,3,opt,name=error,oneof"`
}

func (*QueryResult_Value) isQueryResult_Result() {}
func (*QueryResult_End) isQueryResult_Result()   {}
func (*QueryResult_Error) isQueryResult_Result() {}

func (m *QueryResult) GetResult() isQueryResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *QueryResult) GetValue() *QueryResultValue {
	if x, ok := m.GetResult().(*QueryResult_Value); ok {
		return x.Value
	}
	return nil
}

func (m *QueryResult) GetEnd() *QueryResultEnd {
	if x, ok := m.GetResult().(*QueryResult_End); ok {
		return x.End
	}
	return nil
}

func (m *QueryResult) GetError() *QueryResultError {
	if x, ok := m.GetResult().(*QueryResult_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*QueryResult) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _QueryResult_OneofMarshaler, _QueryResult_OneofUnmarshaler, _QueryResult_OneofSizer, []interface{}{
		(*QueryResult_Value)(nil),
		(*QueryResult_End)(nil),
		(*QueryResult_Error)(nil),
	}
}

func _QueryResult_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*QueryResult)
	// result
	switch x := m.Result.(type) {
	case *QueryResult_Value:
		_ = b.EncodeVarint(1<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Value); err != nil {
			return err
		}
	case *QueryResult_End:
		_ = b.EncodeVarint(2<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.End); err != nil {
			return err
		}
	case *QueryResult_Error:
		_ = b.EncodeVarint(3<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("QueryResult.Result has unexpected type %T", x)
	}
	return nil
}

func _QueryResult_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*QueryResult)
	switch tag {
	case 1: // result.value
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(QueryResultValue)
		err := b.DecodeMessage(msg)
		m.Result = &QueryResult_Value{msg}
		return true, err
	case 2: // result.end
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(QueryResultEnd)
		err := b.DecodeMessage(msg)
		m.Result = &QueryResult_End{msg}
		return true, err
	case 3: // result.error
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(QueryResultError)
		err := b.DecodeMessage(msg)
		m.Result = &QueryResult_Error{msg}
		return true, err
	default:
		return false, nil
	}
}

func _QueryResult_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*QueryResult)
	// result
	switch x := m.Result.(type) {
	case *QueryResult_Value:
		s := proto1.Size(x.Value)
		n += proto1.SizeVarint(1<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *QueryResult_End:
		s := proto1.Size(x.End)
		n += proto1.SizeVarint(2<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *QueryResult_Error:
		s := proto1.Size(x.Error)
		n += proto1.SizeVarint(3<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type QueryResultEnd struct {
}

func (m *QueryResultEnd) Reset()                    { *m = QueryResultEnd{} }
func (m *QueryResultEnd) String() string            { return proto1.CompactTextString(m) }
func (*QueryResultEnd) ProtoMessage()               {}
func (*QueryResultEnd) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{4} }

type QueryResultError struct {
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *QueryResultError) Reset()                    { *m = QueryResultError{} }
func (m *QueryResultError) String() string            { return proto1.CompactTextString(m) }
func (*QueryResultError) ProtoMessage()               {}
func (*QueryResultError) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{5} }

type QueryResultValue struct {
	// Types that are valid to be assigned to Value:
	//	*QueryResultValue_Simple
	//	*QueryResultValue_Compound
	Value isQueryResultValue_Value `protobuf_oneof:"value"`
}

func (m *QueryResultValue) Reset()                    { *m = QueryResultValue{} }
func (m *QueryResultValue) String() string            { return proto1.CompactTextString(m) }
func (*QueryResultValue) ProtoMessage()               {}
func (*QueryResultValue) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{6} }

type isQueryResultValue_Value interface {
	isQueryResultValue_Value()
}

type QueryResultValue_Simple struct {
	Simple *SimpleValue `protobuf:"bytes,1,opt,name=simple,oneof"`
}
type QueryResultValue_Compound struct {
	Compound *CompoundValue `protobuf:"bytes,2,opt,name=compound,oneof"`
}

func (*QueryResultValue_Simple) isQueryResultValue_Value()   {}
func (*QueryResultValue_Compound) isQueryResultValue_Value() {}

func (m *QueryResultValue) GetValue() isQueryResultValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *QueryResultValue) GetSimple() *SimpleValue {
	if x, ok := m.GetValue().(*QueryResultValue_Simple); ok {
		return x.Simple
	}
	return nil
}

func (m *QueryResultValue) GetCompound() *CompoundValue {
	if x, ok := m.GetValue().(*QueryResultValue_Compound); ok {
		return x.Compound
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*QueryResultValue) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _QueryResultValue_OneofMarshaler, _QueryResultValue_OneofUnmarshaler, _QueryResultValue_OneofSizer, []interface{}{
		(*QueryResultValue_Simple)(nil),
		(*QueryResultValue_Compound)(nil),
	}
}

func _QueryResultValue_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*QueryResultValue)
	// value
	switch x := m.Value.(type) {
	case *QueryResultValue_Simple:
		_ = b.EncodeVarint(1<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Simple); err != nil {
			return err
		}
	case *QueryResultValue_Compound:
		_ = b.EncodeVarint(2<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Compound); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("QueryResultValue.Value has unexpected type %T", x)
	}
	return nil
}

func _QueryResultValue_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*QueryResultValue)
	switch tag {
	case 1: // value.simple
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(SimpleValue)
		err := b.DecodeMessage(msg)
		m.Value = &QueryResultValue_Simple{msg}
		return true, err
	case 2: // value.compound
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(CompoundValue)
		err := b.DecodeMessage(msg)
		m.Value = &QueryResultValue_Compound{msg}
		return true, err
	default:
		return false, nil
	}
}

func _QueryResultValue_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*QueryResultValue)
	// value
	switch x := m.Value.(type) {
	case *QueryResultValue_Simple:
		s := proto1.Size(x.Simple)
		n += proto1.SizeVarint(1<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *QueryResultValue_Compound:
		s := proto1.Size(x.Compound)
		n += proto1.SizeVarint(2<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SimpleValue struct {
	// Types that are valid to be assigned to Value:
	//	*SimpleValue_IntValue
	//	*SimpleValue_StringValue
	//	*SimpleValue_Stmt
	//	*SimpleValue_StmtBody
	Value isSimpleValue_Value `protobuf_oneof:"value"`
}

func (m *SimpleValue) Reset()                    { *m = SimpleValue{} }
func (m *SimpleValue) String() string            { return proto1.CompactTextString(m) }
func (*SimpleValue) ProtoMessage()               {}
func (*SimpleValue) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{7} }

type isSimpleValue_Value interface {
	isSimpleValue_Value()
}

type SimpleValue_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=intValue,proto3,oneof"`
}
type SimpleValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=stringValue,proto3,oneof"`
}
type SimpleValue_Stmt struct {
	Stmt *Statement `protobuf:"bytes,3,opt,name=stmt,oneof"`
}
type SimpleValue_StmtBody struct {
	StmtBody *StatementBody `protobuf:"bytes,4,opt,name=stmtBody,oneof"`
}

func (*SimpleValue_IntValue) isSimpleValue_Value()    {}
func (*SimpleValue_StringValue) isSimpleValue_Value() {}
func (*SimpleValue_Stmt) isSimpleValue_Value()        {}
func (*SimpleValue_StmtBody) isSimpleValue_Value()    {}

func (m *SimpleValue) GetValue() isSimpleValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SimpleValue) GetIntValue() int64 {
	if x, ok := m.GetValue().(*SimpleValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *SimpleValue) GetStringValue() string {
	if x, ok := m.GetValue().(*SimpleValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *SimpleValue) GetStmt() *Statement {
	if x, ok := m.GetValue().(*SimpleValue_Stmt); ok {
		return x.Stmt
	}
	return nil
}

func (m *SimpleValue) GetStmtBody() *StatementBody {
	if x, ok := m.GetValue().(*SimpleValue_StmtBody); ok {
		return x.StmtBody
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SimpleValue) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _SimpleValue_OneofMarshaler, _SimpleValue_OneofUnmarshaler, _SimpleValue_OneofSizer, []interface{}{
		(*SimpleValue_IntValue)(nil),
		(*SimpleValue_StringValue)(nil),
		(*SimpleValue_Stmt)(nil),
		(*SimpleValue_StmtBody)(nil),
	}
}

func _SimpleValue_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*SimpleValue)
	// value
	switch x := m.Value.(type) {
	case *SimpleValue_IntValue:
		_ = b.EncodeVarint(1<<3 | proto1.WireVarint)
		_ = b.EncodeVarint(uint64(x.IntValue))
	case *SimpleValue_StringValue:
		_ = b.EncodeVarint(2<<3 | proto1.WireBytes)
		_ = b.EncodeStringBytes(x.StringValue)
	case *SimpleValue_Stmt:
		_ = b.EncodeVarint(3<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Stmt); err != nil {
			return err
		}
	case *SimpleValue_StmtBody:
		_ = b.EncodeVarint(4<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.StmtBody); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SimpleValue.Value has unexpected type %T", x)
	}
	return nil
}

func _SimpleValue_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*SimpleValue)
	switch tag {
	case 1: // value.intValue
		if wire != proto1.WireVarint {
			return true, proto1.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &SimpleValue_IntValue{int64(x)}
		return true, err
	case 2: // value.stringValue
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &SimpleValue_StringValue{x}
		return true, err
	case 3: // value.stmt
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(Statement)
		err := b.DecodeMessage(msg)
		m.Value = &SimpleValue_Stmt{msg}
		return true, err
	case 4: // value.stmtBody
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(StatementBody)
		err := b.DecodeMessage(msg)
		m.Value = &SimpleValue_StmtBody{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SimpleValue_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*SimpleValue)
	// value
	switch x := m.Value.(type) {
	case *SimpleValue_IntValue:
		n += proto1.SizeVarint(1<<3 | proto1.WireVarint)
		n += proto1.SizeVarint(uint64(x.IntValue))
	case *SimpleValue_StringValue:
		n += proto1.SizeVarint(2<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *SimpleValue_Stmt:
		s := proto1.Size(x.Stmt)
		n += proto1.SizeVarint(3<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *SimpleValue_StmtBody:
		s := proto1.Size(x.StmtBody)
		n += proto1.SizeVarint(4<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CompoundValue struct {
	Body []*KeyValuePair `protobuf:"bytes,1,rep,name=body" json:"body,omitempty"`
}

func (m *CompoundValue) Reset()                    { *m = CompoundValue{} }
func (m *CompoundValue) String() string            { return proto1.CompactTextString(m) }
func (*CompoundValue) ProtoMessage()               {}
func (*CompoundValue) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{8} }

func (m *CompoundValue) GetBody() []*KeyValuePair {
	if m != nil {
		return m.Body
	}
	return nil
}

type KeyValuePair struct {
	Key   string       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *SimpleValue `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *KeyValuePair) Reset()                    { *m = KeyValuePair{} }
func (m *KeyValuePair) String() string            { return proto1.CompactTextString(m) }
func (*KeyValuePair) ProtoMessage()               {}
func (*KeyValuePair) Descriptor() ([]byte, []int) { return fileDescriptorNode, []int{9} }

func (m *KeyValuePair) GetValue() *SimpleValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto1.RegisterType((*Ping)(nil), "proto.Ping")
	proto1.RegisterType((*Pong)(nil), "proto.Pong")
	proto1.RegisterType((*QueryRequest)(nil), "proto.QueryRequest")
	proto1.RegisterType((*QueryResult)(nil), "proto.QueryResult")
	proto1.RegisterType((*QueryResultEnd)(nil), "proto.QueryResultEnd")
	proto1.RegisterType((*QueryResultError)(nil), "proto.QueryResultError")
	proto1.RegisterType((*QueryResultValue)(nil), "proto.QueryResultValue")
	proto1.RegisterType((*SimpleValue)(nil), "proto.SimpleValue")
	proto1.RegisterType((*CompoundValue)(nil), "proto.CompoundValue")
	proto1.RegisterType((*KeyValuePair)(nil), "proto.KeyValuePair")
}

func init() { proto1.RegisterFile("node.proto", fileDescriptorNode) }

var fileDescriptorNode = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0x41, 0x6b, 0xdb, 0x30,
	0x14, 0xc7, 0xed, 0xd8, 0xf1, 0x92, 0xe7, 0x6c, 0x18, 0x2d, 0x63, 0x66, 0xec, 0x10, 0xc4, 0xd8,
	0x3c, 0x28, 0x29, 0xa4, 0x97, 0x9e, 0x53, 0x02, 0xa6, 0xbd, 0xa4, 0x2e, 0xf4, 0x9e, 0xd4, 0x22,
	0x98, 0xc6, 0x52, 0x22, 0xcb, 0x85, 0x1c, 0xfa, 0x6d, 0xfa, 0x11, 0xfa, 0x01, 0xcb, 0x93, 0xa5,
	0xd4, 0x6e, 0xc9, 0x49, 0xd6, 0xff, 0xfd, 0xf4, 0x7f, 0xff, 0x27, 0x0b, 0x80, 0x8b, 0x9c, 0x4d,
	0x77, 0x52, 0x28, 0x41, 0xfa, 0x7a, 0xf9, 0x05, 0x95, 0x2a, 0x55, 0x23, 0xd1, 0x00, 0xfc, 0x65,
	0xc1, 0x37, 0x7a, 0x15, 0x7c, 0x43, 0xff, 0xc0, 0xe8, 0xb6, 0x66, 0xf2, 0x90, 0xb1, 0x7d, 0xcd,
	0x2a, 0x45, 0xc6, 0xd0, 0xdf, 0xe3, 0x3e, 0x76, 0x27, 0x6e, 0x32, 0xcc, 0x9a, 0x0d, 0x7d, 0x71,
	0x21, 0x34, 0x58, 0x55, 0x6f, 0x15, 0x39, 0x87, 0xfe, 0xd3, 0x6a, 0x5b, 0x33, 0x4d, 0x85, 0xb3,
	0x9f, 0x8d, 0xf9, 0xb4, 0x85, 0xdc, 0x63, 0x39, 0x75, 0xb2, 0x86, 0x23, 0xff, 0xc1, 0x63, 0x3c,
	0x8f, 0x7b, 0x1a, 0xff, 0xf1, 0x19, 0x5f, 0xf0, 0x3c, 0x75, 0x32, 0x64, 0xd0, 0x9b, 0x49, 0x29,
	0x64, 0xec, 0x9d, 0xf2, 0x5e, 0x60, 0x19, 0xbd, 0x35, 0x37, 0x1f, 0x40, 0x20, 0xb5, 0x4e, 0x23,
	0xf8, 0xd6, 0xf5, 0xa4, 0x09, 0x44, 0x1f, 0x0f, 0xe2, 0x88, 0x4d, 0x03, 0x33, 0xa2, 0xde, 0xd0,
	0xe7, 0x0e, 0xa9, 0xe3, 0x93, 0x33, 0x08, 0xaa, 0xa2, 0xdc, 0x6d, 0xed, 0x9c, 0xc4, 0x64, 0xb9,
	0xd3, 0xa2, 0x1d, 0xd1, 0x30, 0x64, 0x06, 0x83, 0x07, 0x51, 0xee, 0x44, 0x7d, 0x1c, 0x74, 0x6c,
	0xf8, 0x2b, 0x23, 0xdb, 0x13, 0x47, 0x6e, 0xfe, 0xc5, 0x5c, 0x24, 0x7d, 0x75, 0x21, 0x6c, 0xd9,
	0x92, 0xdf, 0x30, 0x28, 0x78, 0x13, 0x43, 0x37, 0xf7, 0xf0, 0x98, 0x55, 0x08, 0x85, 0xb0, 0x52,
	0xb2, 0xe0, 0x9b, 0x06, 0xc0, 0x6e, 0xc3, 0xd4, 0xc9, 0xda, 0x22, 0xf9, 0x0b, 0x3e, 0xfe, 0x77,
	0x73, 0x8d, 0x91, 0x8d, 0xae, 0x56, 0x8a, 0x95, 0x8c, 0xab, 0xd4, 0xc9, 0x74, 0x1d, 0x63, 0xe3,
	0x3a, 0x17, 0xf9, 0x21, 0xf6, 0x3b, 0xb1, 0x8f, 0x2c, 0xd6, 0xb0, 0xbf, 0xe5, 0xde, 0x63, 0x5f,
	0xc2, 0xd7, 0xce, 0x70, 0xe4, 0x1f, 0xf8, 0x6b, 0x74, 0x72, 0x27, 0x5e, 0x12, 0xce, 0xbe, 0x1b,
	0xa7, 0x1b, 0x76, 0xd0, 0xe5, 0xe5, 0xaa, 0x90, 0x99, 0x06, 0xe8, 0x35, 0x8c, 0xda, 0x2a, 0x89,
	0xc0, 0x7b, 0x64, 0xf6, 0xd9, 0xe1, 0x27, 0x49, 0xec, 0x23, 0xeb, 0x9d, 0xba, 0x7c, 0xf3, 0xba,
	0xd6, 0x81, 0xae, 0x5c, 0xbc, 0x05, 0x00, 0x00, 0xff, 0xff, 0x21, 0x5c, 0x63, 0x0f, 0xfc, 0x02,
	0x00, 0x00,
}
